require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - node_modules/**/*

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'
    '%r': '()'

LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 40

Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

BlockLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Capybara/FeatureMethods:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false
