require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - node_modules/**/*
  NewCops: enable
  SuggestExtensions: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'
    '%r': '()'

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/DoubleNegation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

RSpec/BeEq:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false
